name: 'Composable Issue Comments'
description: 'This is a composable action that will write a comment to a GitHub Issue or Pull Request.'
author: 'Froilán Irizarry Rivera'
inputs:
  message:
    description: 'Issue or Pull Request message'
    required: true
  stepStatus:
    description: 'The status of the previous step. This will change the comment body.'
    default: 'failed'
    required: true
  label:
    description: 'A label to add to the issue'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
