name: "build-test"
on: [push, pull_request]

jobs:
  lint-test:
    name: 'Lint and Test Node: ${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '10', '8' ]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node }}-
    - name: Install NPM Packages
      run: npm ci
    - name: lint
      run: npm run lint
    - name: Check Formatting
      run: npm rum format-check
    - name: Run Tests
      run: npm test